import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Body from "../components/Body";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="max-w-7xl mx-auto space-y-4 bg-indigo-400 h-screen select-none">
      <Head>
        <title>Distronix | Internal Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/download.jpg" />
      </Head>

      {/* This header of this page */}
      <Header />

      {/* Body  */}
      <Body />
    </div>
  );
};

export default Home;
